GET http://localhost:3000/admin
Content-Type: application/json

{
    "userId":2
}

###


GET http://localhost:3000/dashboard
Content-Type: application/json

{
    "userId":1
}

###


POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kyle",
    "password": "password"
}


###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Kyle",
    "password": "password"
}